### ISSUE TITLE
Default and recovery messages

### ISSUE THREAD

**Issue by MO-BrandonR** [agperson/zabbix-hipchat-alerts#3]
Hello, I believe you should change the description for the messages to include quoting the values:

name: "{TRIGGER.NAME}"
id: "{TRIGGER.ID}"
status: "{TRIGGER.STATUS}"
hostname: "{HOSTNAME}"
ip: "{IPADDRESS}"
value: "{TRIGGER.VALUE}"
event_id: "{EVENT.ID}"
severity: "{TRIGGER.SEVERITY}"

Otherwise triggers with special characters like [ ] : don't get sent.  I assume this is due to the YAML read but didn't test in depth as I'm not familiar at all with ruby.  I was able to confirm a number of alerts that weren't being received via hipchat before were afterward.

Regards,
Brandon

**Comment by agperson** [comment]
Thanks for the feedback, I have updated the README to reflect this recommendation.
